### ISSUE TITLE
TabNine process restart limit reached

### ISSUE THREAD

**Issue by Iorest** [TommyX12/company-tabnine#36] opened 2020-07-14 07:00 UTC
When I call `company-tabnine` , error occurs,

> TabNine server started.
> Company: An error occurred in auto-begin
> Company: backend company-tabnine error "Process company-tabnine--process not running" with args (prefix)
> user-error: Cannot complete at point
> TabNine process #<process company-tabnine--process> received event "killed: 9
> ".
> TabNine process restart limit reached.

I use  MacOS.

**Comment by halftan** [comment] 2020-09-24 11:59
That might be caused by a partially downloaded binary. You can download it manually from `https://update.tabnine.com/${version}/x86_64-apple-darwin/TabNine` . Replace `${version}` with the latest version fetched from https://update.tabnine.com/version . `chmod +x ` the downloaded binary and place it under `$HOME/.TabNine/${version}/x86_64-apple-darwin/`.

**Comment by NathanLovato** [comment] 2020-11-26 16:26
I can confirm the issue. Trying to download any file from update.tabnine.com with wget returns a 403 error: access forbidden. Tabnine stopped working today after an update.

```sh
wget https://update.tabnine.com/3.2.25/x86_64-apple-darwin/TabNine
--2020-11-26 10:25:09--  https://update.tabnine.com/3.2.25/x86_64-apple-darwin/TabNine
Resolving update.tabnine.com (update.tabnine.com)... 143.204.151.5, 143.204.151.77, 143.204.151.8, ...
Connecting to update.tabnine.com (update.tabnine.com)|143.204.151.5|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-11-26 10:25:09 ERROR 403: Forbidden.
```
Any idea on how to work around that?

**Comment by NathanLovato** [comment] 2020-11-26 19:10
This was fixed by the developers, it was an error on the version number on their side.

**Comment by Iorest** [comment] 2020-11-27 02:03
Yeah,my problem is fixed.

**Comment by NathanLovato** [comment] 2020-11-27 03:55
@Iorest in this case, you can close the issue.

**Closed as completed** 2020-11-28 08:47 UTC
