### ISSUE TITLE
Error while complete file path

### ISSUE THREAD

**Issue by yqrashawn** [TommyX12/company-tabnine#10] opened 2018-12-30 01:55 UTC
```
Debugger entered--Lisp error: (json-string-format "?\\C-@")
  signal(json-string-format ("?\\C-@"))
  json-read-string()
  json-read()
  json-read-object()
  json-read()
  json-read-array()
  json-read()
  json-read-object()
  json-read()
  json-read-from-string("{\"suffix_to_substitute\":\"B\",\"results\":[{\"result\":\"Bee.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BitBar.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Boom 3D.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blender.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BearyChat.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Basecamp 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blenderplayer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Backup and Sync.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"iBooks.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"qBittorrent.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"AnyBar.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"KextBeast.pkg\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Font Book.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"MultiBeast.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Photo Booth.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Kitematic (Beta).app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Robo 3T.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Sublime Text.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tongbu.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Numbers.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keybase.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dropbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tweetbot.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Cakebrew.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Enjoyable.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dashboard.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Geekbench 4.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keyboard Maestro.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-Elements.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-EventViewer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch Toolbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"NativeDisplayBrightness.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"YY.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Setapp.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Safari.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Remacs.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Reeder.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Photos.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"IDLE 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Flinto.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dota 2.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Docker.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Deluge.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"ClashX.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".localized\",\"prefix_to_substitute\":\"\"},{\"result\":\"Thunder.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Textua")
  company-tabnine--decode("{\"suffix_to_substitute\":\"B\",\"results\":[{\"result\":\"Bee.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BitBar.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Boom 3D.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blender.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BearyChat.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Basecamp 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blenderplayer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Backup and Sync.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"iBooks.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"qBittorrent.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"AnyBar.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"KextBeast.pkg\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Font Book.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"MultiBeast.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Photo Booth.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Kitematic (Beta).app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Robo 3T.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Sublime Text.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tongbu.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Numbers.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keybase.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dropbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tweetbot.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Cakebrew.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Enjoyable.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dashboard.app\",\"prefix_to_substitute\":\"\"},
{\"result\":\"Geekbench 4.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keyboard Maestro.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-Elements.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-EventViewer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch Toolbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"NativeDisplayBrightness.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"YY.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Setapp\",\"prefix_to_substitute\":\"\"},{\"result\":\"mpv.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Paw.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Siri.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Maps.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Mail.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Logitech\",\"prefix_to_substitute\":\"\"},{\"result\":\"IINA.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"IDLE.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Folx.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Flux.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dash.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".gitkeep\",\"prefix_to_substitute\":\"\"},{\"result\":\"iTerm.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Xcode.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Utilities\",\"prefix_to_substitute\":\"\"},{\"result\":\"Surge.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Steam.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Spark.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Slack.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Pages.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Notes.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Marta.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Lumen.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Ivacy.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Eudic.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Emacs.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Chess.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".DS_Store\",\"prefix_to_substitute\":\"\"},{\"result\":\"iTunes.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"WeChat.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"V2RayX.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Setapp.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Safari.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Remacs.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Reeder.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Photos.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"IDLE 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Flinto.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dota 2.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Docker.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Deluge.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"ClashX.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".localized\",\"prefix_to_substitute\":\"\"},{\"result\":\"Thunder.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Textua")
  company-tabnine--process-filter(#<process company-tabnine--process> "{\"suffix_to_substitute\":\"B\",\"results\":[{\"result\":\"Bee.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BitBar.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Boom 3D.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blender.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"BearyChat.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Basecamp 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Blenderplayer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Backup and Sync.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"iBooks.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"qBittorrent.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"AnyBar.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"KextBeast.pkg\",\"prefix_to_substitute\":\"\"},{\"result\":\"Font Book.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"MultiBeast.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Photo Booth.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Kitematic (Beta).app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Robo 3T.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sublime Text.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tongbu.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Numbers.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keybase.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dropbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Tweetbot.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Cakebrew.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Enjoyable.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dashboard.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Geekbench 4.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Keyboard Maestro.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-Elements.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Karabiner-EventViewer.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch Toolbox.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"NativeDisplayBrightness.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"YY.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Setapp\",\"prefix_to_substitute\":\"\"},{\"result\":\"mpv.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Paw.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Siri.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Maps.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Mail.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Logitech\",\"prefix_to_substitute\":\"\"},{\"result\":\"IINA.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"IDLE.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Folx.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Flux.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dash.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".gitkeep\",\"prefix_to_substitute\":\"\"},{\"result\":\"iTerm.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Xcode.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Utilities\",\"prefix_to_substitute\":\"\"},{\"result\":\"Surge.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Steam.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Spark.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Slack.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Pages.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Notes.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Marta.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Lumen.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Ivacy.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Eudic.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Emacs.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Chess.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".DS_Store\",\"prefix_to_substitute\":\"\"},{\"result\":\"iTunes.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"WeChat.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"V2RayX.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Sketch.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Setapp.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Safari.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Remacs.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Reeder.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Photos.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"IDLE 3.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Flinto.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Dota 2.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Docker.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Deluge.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"ClashX.app\",\"prefix_to_substitute\":\"\"},{\"result\":\".localized\",\"prefix_to_substitute\":\"\"},{\"result\":\"Thunder.app\",\"prefix_to_substitute\":\"\"},{\"result\":\"Textua")
  accept-process-output(#<process company-tabnine--process> 0.25)
  company-tabnine-send-request((:version "0.11.1" :request (:Autocomplete (:before "                [:open_bracket [:!Tx :!T9 :open_bracket]]\n                 [:close_bracket [:!Tx :!T9 :close_bracket]]]}\n        {:des \"Vi Mode [D as Trigger Key]\"\n         :rules [:vi-mode\n                 [:##j :down_arrow]\n                 [:##k :up_arrow]\n                 [:##h :left_arrow]\n                 [:##l :right_arrow]\n                 [:##b :!Oleft_arrow]\n                 [:##w :!Oright_arrow]\n                 [:##0 :!Ta]\n                 [:##4 :!Te]]}\n        {:des \"Vi Visual Mode\"\n         :rules [:vi-visual-mode\n                 [:##j :!Sdown_arrow]\n                 [:##k :!Sup_arrow]\n                 [:##h :!Sleft_arrow]\n                 [:##l :!Sright_arrow]\n                 [:##b :!SOleft_arrow]\n                 [:##w :!SOright_arrow]\n                 [:##0 :!SCleft_arrow]\n                 [:##4 :!SCright_arrow]\n                 [:##open_bracket :!SOup_arrow]\n                 [:##close_bracket :!SOdown_arrow]]}\n        {:des \"Emacs switch buffer\"\n         :rules [:Emacs\n                 [:tab :!Ttab :period-mode]\n                 [:tab :!TStab :comma-mode]]}\n        {:des \"launcher mode\"\n         :rules [:launch-mode\n                 [:j [:open \"/Applications/Alacritty.app\"]]\n                 [:k [:open \"/Applications/Emacs.app\"]]\n                 [:l [:open \"/Applications/Google Chrome Canary.app/\"]]\n                 [:m [:open \"/Applications/Mail.app\"]]\n                 [:v [:open \"/Applications/WeChat.app\"]]\n                 [:q [:open \"/Applications/Karabiner-Elements.app\"]]\n                 [:f [:open \"/Applications/Finder.app\"]]\n                 [:9 [:open \"/Applications/PDF Expert.app\"]]\n                 [:comma [:open \"/Applications/Safari.app\"]]\n                 [:h [:open \"/Applications/Bee.app\"]]\n                 [:period [:open \"/Applications/Paw.app\"]]\n                 [:equal_sign [:open \"/Applications/Textual.app\"]]\n                 [:8 [:open \"/Applications/Karabiner-EventViewer.app\"]]\n                 [:b [:launch \"/Applications/B" :after "\"]]\n                 [:c [:launch \"VSCode\"]]\n                 [:t [:launch \"2do\"]]\n                 [:r [:launch \"Timing\"]]\n                 ;; [:t [:launch \"Pagico\"]]\n                 #_[:l [:!Cgrave_accent_and_tilde] :Chromes]\n                 [:d [{:key :n :modi [:right_option]} {:key :d :modi [:right_option]} {:key :b :modi [:right_option]} :return_or_enter]]]}\n        {:des \"caps_lock\"\n         :rules [[:##caps_lock :left_control nil {:alone :escape}]]}\n        {:des \"HHKB, FILCO MINILA Change left control to esc if alone\"\n         :rules [[:##left_control :left_control [:hhkb-bt :hhkb :hhkb-tmk :filco-minila] {:alone :escape}]]}\n        {:des \"Change right_command to command-tab when used alone\"\n         :rules [[:right_command :right_command nil {:alone [:!Ctab]}]\n                 [:application :right_command nil {:alone [:!Ctab]}]]}\n        {:des \"Change left_option to f18 when used alone\"\n         :rules [[:left_option :left_option nil {:alone [:f18]}]]}\n        {:des \"Quit application by pressing command-q twice\"\n         :rules [[:!C#Pq [:!Cq [\"command-q\" 0]] [\"command-q\" 1]]\n                 [:!C#Pq [\"command-q\" 1] nil {:delayed {:invoked [\"command-q\" 0] :canceled [\"commandq\" 0]}}]]}\n        {:des \"Change right_option to switch to second recent application when used alone\"\n         :rules [[:right_option :right_option nil {:alone [\"osascript ~/Dropbox/sync/Automator/switch-to-second-previous-app.scpt\"]}]]}\n        {:des \"some simultaneous keys\"\n         :rules [[[:h :l] [:alf \"helpSearch\" \"com.tedwise.menubarsearch\"]]\n                 [[:j :l] [:f19 [\"in-alfred\" 1]]]]}\n        {:des \"alfred mode\"\n         :rules [[:l :!COi :browsers-alfred-mode]\n                 [:l :!CTslash [:finder-alfred-mode [\"in-alfred\" 1]]]\n                 :alfred-mode\n                 [:h [[:alf \"search repos\" \"me.lachlan.githubjump\"] [\"in-alfred\" 1]]]\n                 [:j [:alf \"searchGithub\" \"nikivi.search-the-web\"]]\n                 [:return_or_enter [:alf \"web searches\" \"nik" :filename "/Users/yqrashawn/.config/karabiner.edn" :region_includes_beginning :json-false :region_includes_end :json-false :max_num_results 10))))
  company-tabnine-query()
  company-tabnine(prefix)
  apply(company-tabnine prefix)
  company-call-backend-raw(prefix)
  apply(company-call-backend-raw prefix)
  company--force-sync(company-call-backend-raw (prefix) company-tabnine)
  company-call-backend(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer karabiner.edn> #<window 24 on *scratch*> 82662 7583)
  apply(company-idle-begin (#<buffer karabiner.edn> #<window 24 on *scratch*> 82662 7583))
  timer-event-handler([t 23592 9312 622957 nil company-idle-begin (#<buffer karabiner.edn> #<window 24 on *scratch*> 82662 7583) nil 0])
```

message buffer
```
error in process filter: json-read-string: Bad string format: "?\\C-@"
error in process filter: Bad string format: "?\\C-@"
error in process filter: Unrecognized keyword: "te" [2 times]
error in process filter: json-read: JSON readtable error: 115
error in process filter: JSON readtable error: 115
error in process filter: json-read-string: Bad string format: "?\\C-@"
error in process filter: Bad string format: "?\\C-@"
error in process filter: json-read: JSON readtable error: 95
error in process filter: JSON readtable error: 95
Company: An error occurred in auto-begin
Company: backend company-tabnine error "Wrong type argument: listp, "},{"" with args (prefix)
```

**Comment by Deewiant** [comment] 2019-02-15 14:42
I can confirm this as well. It's easy to trigger with a directory with lots of files in it: typing `/lib/` or `/usr/lib/` works for me, for example.

It seems that the issue is that `make-process` uses a 4096-byte buffer internally, so `company-tabnine--process-filter` isn't necessarily called with the full JSON response from TabNine, which can be much longer than that. This is especially annoying because there are actually multiple errors, one for each 4096-byte chunk of the response, since of course each chunk fails to decode. There's some quite noticeable freezing in the UI when this happens, which I hope is due to the errors and not because emacs can't read and decode the response quickly enough...

I presume this could be fixed by something along the lines of having a (buffer-local?) variable into which `company-tabnine--process-filter` accumulates what it sees, only calling `company-tabnine--decode` once the terminating `\n` character is encountered.

**Comment by bkudria** [comment] 2019-02-15 22:14
Is this an instance of https://nullprogram.com/blog/2018/01/17/ ?

**Comment by yqrashawn** [comment] 2019-02-16 00:51
Same problem here.

[Rashawn Zhang - Contact Using Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=pmzue4)

On February 15, 2019 at 22:14 GMT, Benjamin Kudria <notifications@github.com> wrote:

Is this an instance of https://nullprogram.com/blog/2018/01/17/ ?

**Comment by TommyX12** [comment] 2019-07-04 06:00
Should be fixed in the latest commit.

**Closed as completed by TommyX12** 2019-07-04 06:00 UTC
Labels: bug
